<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BaliIndonesia</name>
   <tag></tag>
   <elementGuidId>f1cebaff-9822-4f89-aa51-fe9f366d04c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-hotel']/div/div/div[2]/div/div/div/div[3]/div[2]/div/div/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tix-col-9 tix-row-nowrap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BaliIndonesia</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-hotel&quot;)/div[@class=&quot;section-main&quot;]/div[@class=&quot;home-slider-form&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;home-form level-2-index&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tix-row&quot;]/div[@class=&quot;tix-col-6 tix-row-nowrap&quot;]/div[@class=&quot;tix-col-10 tix-column-nowrap b-bot-bbb&quot;]/div[@class=&quot;destination-select-container select-box tix-text-size-1 tix-py-0625&quot;]/div[@class=&quot;select-box-dialog destination-select level-1-index fadeInDown-exit fadeInDown-exit-active&quot;]/div[@class=&quot;tix-column-nowrap&quot;]/div[@class=&quot;dialog-content&quot;]/div[@class=&quot;tix-column-nowrap&quot;]/div[@class=&quot;scrollable-dialog-content tix-column-nowrap tix-pb-1875 tix-pt-05&quot;]/div[@class=&quot;dest-items tix-row-nowrap tix-border-bottom tix-py-075 tix-px-1125&quot;]/div[@class=&quot;tix-col-9 tix-row-nowrap&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='home-hotel']/div/div/div[2]/div/div/div/div[3]/div[2]/div/div/div/div[2]/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kota Tujuan atau Nama Hotel'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div[2]/div/div/div/div[2]/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
